CREATE TABLE questions(
id SERIAL PRIMARY KEY,
question TEXT NOT NULL,
correct TEXT NOT NULL,
incorrect TEXT[] NOT NULL,
explanation TEXT NOT NULL,
img_url TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);